allowBuilds:
  better-sqlite3: true
  msgpackr-extract: false
  unrs-resolver: false

nodeLinker: hoisted

patchedDependencies:
  "@react-native/gradle-plugin@0.85.3": patches/@react-native__gradle-plugin@0.85.3.patch
